import { Climb } from "@/components/climbs/columns";

export const climbs: Climb[] = [
    {
        climb_id: 1,
        name: "The Overhang Beast",
        date: new Date("2025-04-15"),
        location: "The Hive North Shore",
        grade: "V4",
        type: "boulder",
        environment: "indoor",
        attempts: 3,
        note: "Tough overhang, got it on the third go!",
        attachemnt: "hive-ns-v4.jpg",
    },
    {
        climb_id: 2,
        name: "Smoke Signals",
        date: new Date("2025-04-16"),
        location: "Squamish - Smoke Bluffs",
        grade: "5.10a",
        type: "lead",
        environment: "outdoor",
        attempts: 1,
        note: "Clean send! Great weather.",
        attachemnt: "smoke-bluffs-lead.jpg",
    },
    {
        climb_id: 3,
        name: "The Crux Conqueror",
        date: new Date("2025-04-17"),
        location: "Cliffhanger Vancouver",
        grade: "5.11b",
        type: "top-rope",
        environment: "indoor",
        attempts: 4,
        note: "Struggled with the crux, but finished it.",
        attachemnt: "cliffhanger-511b.jpg",
    },
    {
        climb_id: 4,
        name: "Chill Start",
        date: new Date("2025-04-18"),
        location: "The Hive Surrey",
        grade: "V2",
        type: "boulder",
        environment: "indoor",
        attempts: 1,
        note: "Easy warm-up route.",
        attachemnt: "hive-surrey-v2.jpg",
    },
    {
        climb_id: 5,
        name: "Slab Mastery",
        date: new Date("2025-04-20"),
        location: "Squamish - The Apron",
        grade: "5.9",
        type: "lead",
        environment: "outdoor",
        attempts: 2,
        note: "Fun slab climb, took a rest halfway up.",
        attachemnt: "apron-slab.jpg",
    },
];
