import { Climb } from "./components/climbs/columns";

export const climbs: Climb[] = [
    {
        climb_id: 1,
        name: "The Overhang Beast",
        date: new Date("2025-04-15"),
        location: "The Hive North Shore",
        grade: "V4",
        type: "boulder",
        environment: "indoor",
        attempts: 3,
        note: "Tough overhang, got it on the third go!",
        attachment: "hive-ns-v4.jpg",
    },
    {
        climb_id: 2,
        name: "Smoke Signals",
        date: new Date("2025-04-16"),
        location: "Squamish - Smoke Bluffs",
        grade: "5.10a",
        type: "lead",
        environment: "outdoor",
        attempts: 1,
        note: "Clean send! Great weather.",
        attachment: "smoke-bluffs-lead.jpg",
    },
    {
        climb_id: 3,
        name: "The Crux Conqueror",
        date: new Date("2025-04-17"),
        location: "Cliffhanger Vancouver",
        grade: "5.11b",
        type: "top-rope",
        environment: "indoor",
        attempts: 4,
        note: "Struggled with the crux, but finished it.",
        attachment: "cliffhanger-511b.jpg",
    },
    {
        climb_id: 4,
        name: "Chill Start",
        date: new Date("2025-04-18"),
        location: "The Hive Surrey",
        grade: "V2",
        type: "boulder",
        environment: "indoor",
        attempts: 1,
        note: "Easy warm-up route.",
        attachment: "hive-surrey-v2.jpg",
    },
    {
        climb_id: 5,
        name: "Slab Mastery",
        date: new Date("2025-04-20"),
        location: "Squamish - The Apron",
        grade: "5.9",
        type: "lead",
        environment: "outdoor",
        attempts: 2,
        note: "Fun slab climb, took a rest halfway up.",
        attachment: "apron-slab.jpg",
    },
    {
        climb_id: 6,
        name: "The Overhang Beast",
        date: new Date("2025-04-15"),
        location: "The Hive North Shore",
        grade: "V4",
        type: "boulder",
        environment: "indoor",
        attempts: 3,
        note: "Tough overhang, got it on the third go!",
        attachment: "hive-ns-v4.jpg",
    },
    {
        climb_id: 7,
        name: "Smoke Signals",
        date: new Date("2025-04-16"),
        location: "Squamish - Smoke Bluffs",
        grade: "5.10a",
        type: "lead",
        environment: "outdoor",
        attempts: 1,
        note: "Clean send! Great weather.",
        attachment: "smoke-bluffs-lead.jpg",
    },
    {
        climb_id: 8,
        name: "The Crux Conqueror",
        date: new Date("2025-04-17"),
        location: "Cliffhanger Vancouver",
        grade: "5.11b",
        type: "top-rope",
        environment: "indoor",
        attempts: 4,
        note: "Struggled with the crux, but finished it.",
        attachment: "cliffhanger-511b.jpg",
    },
    {
        climb_id: 9,
        name: "Chill Start",
        date: new Date("2025-04-18"),
        location: "The Hive Surrey",
        grade: "V2",
        type: "boulder",
        environment: "indoor",
        attempts: 1,
        note: "Easy warm-up route.",
        attachment: "hive-surrey-v2.jpg",
    },
    {
        climb_id: 10,
        name: "Slab Mastery",
        date: new Date("2025-04-20"),
        location: "Squamish - The Apron",
        grade: "5.9",
        type: "lead",
        environment: "outdoor",
        attempts: 2,
        note: "Fun slab climb, took a rest halfway up.",
        attachment: "apron-slab.jpg",
    },
    {
        climb_id: 11,
        name: "Chill Start",
        date: new Date("2025-04-18"),
        location: "The Hive Surrey",
        grade: "V2",
        type: "boulder",
        environment: "indoor",
        attempts: 1,
        note: "Easy warm-up route.",
        attachment: "hive-surrey-v2.jpg",
    },
    {
        climb_id: 12,
        name: "Slab Mastery",
        date: new Date("2025-04-20"),
        location: "Squamish - The Apron",
        grade: "5.9",
        type: "lead",
        environment: "outdoor",
        attempts: 2,
        note: "Fun slab climb, took a rest halfway up.",
        attachment: "apron-slab.jpg",
    },
];

// CREATE TABLE climb (
//     climb_id SERIAL PRIMARY KEY,
//     name VARCHAR(30),
//     date DATE DEFAULT now(),
//     location VARCHAR(30),
//     grade VARCHAR(10),
//     type VARCHAR(30),
//     environment VARCHAR(30),
//     flash BOOLEAN,
//     note VARCHAR(30),
//     attachment VARCHAR(30)
// );

// INSERT INTO climb (name, location, grade, type, environment, flash, note, attachment)
//     VALUES ('Slab Mastery', 'Squamish', '5.9', 'lead', 'outdoor', TRUE, 'Fun slab climb', 'apron-slab.jpg');